name: PROD Deployment

on:
  workflow_dispatch:

env:
  PROJECT_ID: plucky-plexus-413716
  SERVICE: charizard
  REGION: us-central1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # - name: Use Node.js 16.x
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '16.x'

      # - name: Install dependencies
      #   run: npm ci --legacy-peer-deps

      # - name: Run lint and prettier
      #   run: |
      #     npm run lint
      #     npm run prettier:check

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: ./
